

import { Account, Category, TransactionType, StorageConfig, Ledger, UserProfile, UIPreferences, AIConfig } from './types';
import { 
  Wallet, CreditCard, Banknote, Briefcase, ShoppingBag, Coffee, Car, Home, 
  Film, Utensils, Smartphone, Cloud, HardDrive, Server, Bus, Plane, 
  ShoppingCart, Gift, Gamepad2, Dumbbell, Stethoscope, Zap, Wifi,
  Baby, GraduationCap, Globe, TrendingUp, Users, HandCoins, ArrowRightLeft, Undo2
} from 'lucide-react';
import React from 'react';

// NOTE: EXCHANGE_RATES has been moved to services/currencyService.ts and is now fetched dynamically.

export const CURRENCY_SYMBOLS: Record<string, string> = {
  'USD': '$',
  'CNY': '¥',
  'EUR': '€',
  'JPY': '¥',
  'GBP': '£',
  'HKD': '$',
  'CHF': 'Fr',
};

export const DEFAULT_AI_CONFIG: AIConfig = {
  provider: 'GEMINI',
  apiKey: process.env.API_KEY || '',
  model: 'gemini-1.5-flash',
  baseUrl: ''
};

// Translations
export const I18N = {
  en: {
    dashboard: 'Overview',
    reports: 'Stats',
    accounts: 'Accounts',
    settings: 'Settings',
    storage: 'Storage',
    local: 'Local Device',
    cloud: 'iCloud Sync',
    nas: 'WebDAV / NAS',
    server: 'Self-Hosted',
    totalBalance: 'Net Worth',
    expenses: 'Exp',
    income: 'Inc',
    spendingActivity: 'Activity',
    newTransaction: 'New',
    save: 'Save',
    cancel: 'Cancel',
    parse: 'AI Parse',
    manual: 'Manual',
    parsing: 'Thinking...',
    description: 'Note',
    category: 'Category',
    subCategory: 'Sub-Category',
    date: 'Date',
    amount: 'Amount',
    merchant: 'Merchant',
    looksGood: 'Review',
    edit: 'Edit',
    saveTx: 'Save Record',
    describeTx: 'Paste text or speak...',
    aiTip: 'e.g. $20 McDonald\'s lunch yesterday via Credit Card',
    myLedgers: 'My Ledgers',
    addLedger: 'Create Ledger',
    userProfile: 'Profile',
    language: 'Language',
    name: 'Name',
    storageDesc: 'Data synchronization settings.',
    selectCategory: 'Select Category',
    account: 'Account',
    type: 'Type',
    addAccount: 'Add Account',
    expense: 'Expense',
    transfer: 'Transfer',
    profile: 'Profile',
    data: 'Data Management',
    ledgers: 'Ledgers',
    currency: 'Currency',
    initialBalance: 'Balance / Debt',
    create: 'Create',
    editLedger: 'Edit Ledger',
    currentBook: 'Current Book',
    allTransactions: 'Recent Activity',
    viewAll: 'Show All',
    noTransactions: 'No transactions found.',
    netWorth: 'Net Assets',
    manageCategories: 'Manage Categories',
    addCategory: 'Add Category',
    delete: 'Delete',
    color: 'Color',
    icon: 'Icon',
    history: 'History',
    searchPlaceholder: 'Search transactions...',
    backup: 'Backup & Restore',
    export: 'Export Data (JSON)',
    import: 'Import Data',
    exportDesc: 'Download all your data as a file.',
    importDesc: 'Restore data from a backup file.',
    success: 'Success',
    error: 'Error',
    serverAddress: 'Server URL',
    username: 'Username',
    password: 'Password',
    apiKey: 'API Key',
    connect: 'Connect',
    btn_test_connection: 'Test Connection',
    dayExp: 'Exp',
    dayInc: 'Inc',
    logOut: 'Log Out',
    viewProfile: 'View Profile',
    selectDate: 'Select Date',
    confirmDelete: 'Delete this transaction?',
    smartImport: 'Smart Import',
    screenshotImport: 'Screenshot Recognition',
    csvImport: 'WeChat/Alipay Import',
    analyzing: 'Analyzing Image...',
    parsingCsv: 'Parsing CSV...',
    importedCount: 'transactions imported.',
    includeInTotal: 'Include in Net Worth',
    assets: 'Assets',
    liabilities: 'Liabilities & Credit',
    creditLimit: 'Credit Limit',
    billDay: 'Statement Day',
    repayDay: 'Repayment Day',
    interestRate: 'Interest Rate (APR)',
    dueDate: 'Due Date',
    daysLeft: 'days left',
    utilization: 'Used',
    available: 'Available',
    installments: 'Installment Plan',
    current: 'Current',
    total: 'Total',
    upcomingBills: 'Upcoming Bills',
    noUpcomingBills: 'No upcoming bills due soon.',
    isInstallment: 'Installment?',
    period: 'Period',
    financialReminders: 'Financial Reminders',
    interestFee: 'Interest / Fee',
    totalCost: 'Total Cost',
    activeInstallments: 'Active Installments',
    monthlyPayment: 'Monthly Payment',
    remainingPrincipal: 'Remaining Principal',
    earlyRepayment: 'Early Repayment',
    confirmEarlyRepayment: 'Confirm early repayment of the remaining balance?',
    planDetails: 'Plan Details',
    resetData: 'Reset Data',
    confirmReset: 'Are you sure you want to delete all data? This action cannot be undone.',
    resetComplete: 'Cleanup complete.',
    appearance: 'Appearance & Navigation',
    showReports: 'Show Stats Tab',
    showAccounts: 'Show Accounts Tab',
    
    // Batch Operations
    selected: 'Selected',
    batchDelete: 'Delete',
    batchCancel: 'Cancel',
    confirmBatchDelete: 'Are you sure you want to delete {count} transactions?',

    // AI Settings
    aiConfig: 'AI Model Config',
    provider: 'Provider',
    modelName: 'Model Name',
    baseUrl: 'Base URL',
    apiKeyPlaceholder: 'Enter API Key',

    // New Additions for Full Localization
    loading: 'Loading ZenLedger...',
    importBackup: 'Import Backup',
    overwrite: 'Overwrite Existing Data',
    merge: 'Merge with Existing',
    customizeNav: 'Customize your Bottom Navigation Bar',
    aiAdvisor: 'AI Financial Coach',
    monthlyAnalysis: 'Monthly Analysis',
    thinking: 'Thinking...',
    kuruKuru: 'Crunching numbers... Detecting bad financial decisions...',
    gotIt: 'Got it',
    expensesByCat: 'Expenses by Category',
    incomeByCat: 'Income by Category',
    noActivePlan: 'No active installment plans.',
    moodHappy: 'Happy',
    moodNeutral: 'Neutral',
    moodRegret: 'Regret',
    moodSplurge: 'Splurge',
    exchangeRate: 'Exchange Rate',
    reset: 'Reset',
    confirm: 'Confirm',
    installmentOn: 'Installment On',
    active: 'Active',
    owed: 'owed',
    rateUpdated: 'Rates updated:',
    
    // New Dashboard Keys
    monthlyExpense: 'Monthly Expense',
    monthlyIncome: 'Monthly Income',
    monthlyBalance: 'Balance',
    totalLiabilities: 'Total Liabilities',
    totalAssets: 'Total Assets',
    
    // Missing Keys Added
    settingsSaved: 'Settings Saved!',
    enterApiKey: 'Please enter an API Key',
    testingConnection: 'Testing Connection...',
    connectionSuccess: 'Connection Successful!',
    connectionFailed: 'Connection Failed:',
    backupDownloaded: 'Backup downloaded successfully.',
    invalidJson: 'Invalid JSON file or corrupted backup.',
    noValidTxs: 'No valid transactions found.',
    webOnly: 'Web Only',
    webNasWarning: 'Web client cannot connect directly to NAS due to browser security. Backup downloaded instead.',
    nasCorsWarning: 'Web Browser limitations (CORS) may block connections to local NAS IP addresses. If connection fails, please ensure your NAS allows cross-origin requests or use HTTPS.',
    enterModelName: 'Enter model name (e.g. gpt-4)',
    defaultUrl: 'Default: https://api.deepseek.com',
    moreOptions: 'More options...',
    charts: 'Charts',
    calendar: 'Calendar',
    freshStart: 'Fresh Start',
    startTx: 'Start with your first transaction',
    hidden: 'Hidden',
    overdue: 'Overdue',
    used: 'Used',
    noAccountsFound: 'No accounts found! Please create an account first.',
    importPrompt: 'How would you like to import this backup?',
    planRepaid: 'Plan marked as Repaid.',
    failedReport: 'Failed to generate report.',
    
    // WebDAV Specifics
    backupNow: 'Backup Now',
    restore: 'Restore',
    autoSync: 'Auto Sync on Startup',
    corsError: 'Connection failed. Likely a CORS issue or invalid URL. Check console for details.',
    backingUp: 'Backing up...',
    restoring: 'Restoring...',
    restoreSuccess: 'Data restored successfully from WebDAV.',
    backupSuccess: 'Backup uploaded successfully.',
    
    accTypes: {
      CHECKING: 'Checking',
      SAVINGS: 'Savings',
      CREDIT_CARD: 'Credit Card',
      CASH: 'Cash',
      INVESTMENT: 'Investment',
      ALIPAY: 'Alipay',
      WECHAT: 'WeChat',
      HUABEI: 'Huabei',
      DEBT: 'Debt (Payable)',
      RECEIVABLE: 'Receivable'
    }
  },
  zh: {
    dashboard: '概览',
    reports: '统计',
    accounts: '账户',
    settings: '设置',
    storage: '存储',
    local: '本地存储',
    cloud: 'iCloud 同步',
    nas: 'WebDAV / NAS',
    server: '自建服务器',
    totalBalance: '净资产',
    expenses: '支出',
    income: '收入',
    spendingActivity: '趋势',
    newTransaction: '记一笔',
    save: '保存',
    cancel: '取消',
    parse: 'AI 识别',
    manual: '手动记账',
    parsing: '分析中...',
    description: '备注',
    category: '分类',
    subCategory: '子分类',
    date: '日期',
    amount: '金额',
    merchant: '商户',
    looksGood: '确认信息',
    edit: '修改',
    saveTx: '保存',
    describeTx: '粘贴文本或语音...',
    aiTip: '例如：昨天微信支付麦当劳午饭30元',
    myLedgers: '我的账本',
    addLedger: '新建账本',
    userProfile: '个人资料',
    language: '语言',
    name: '昵称',
    storageDesc: '数据同步与存储设置。',
    selectCategory: '选择分类',
    account: '账户',
    type: '类型',
    addAccount: '添加账户',
    expense: '支出',
    transfer: '转账',
    profile: '个人',
    data: '数据管理',
    ledgers: '账本管理',
    currency: '币种',
    initialBalance: '余额 / 欠款',
    create: '创建',
    editLedger: '编辑账本',
    currentBook: '当前账本',
    allTransactions: '近期动态',
    viewAll: '查看全部',
    noTransactions: '本月暂无交易记录',
    netWorth: '净资产',
    manageCategories: '管理分类',
    addCategory: '添加分类',
    delete: '删除',
    color: '颜色',
    icon: '图标',
    history: '历史明细',
    searchPlaceholder: '搜索交易...',
    backup: '备份与恢复',
    export: '导出数据 (JSON)',
    import: '导入数据',
    exportDesc: '下载所有数据备份。',
    importDesc: '从备份文件恢复数据。',
    success: '成功',
    error: '错误',
    serverAddress: '服务器地址',
    username: '用户名',
    password: '密码',
    apiKey: 'API 密钥',
    connect: '连接测试',
    btn_test_connection: '测试连接',
    dayExp: '支',
    dayInc: '收',
    logOut: '退出登录',
    viewProfile: '查看资料',
    selectDate: '选择时间',
    confirmDelete: '确认删除这笔账单吗？',
    smartImport: '智能导入',
    screenshotImport: '截图账单识别',
    csvImport: '微信/支付宝账单导入',
    analyzing: '正在识别图片...',
    parsingCsv: '正在解析账单...',
    importedCount: '笔交易已导入',
    includeInTotal: '计入净资产',
    assets: '资产账户',
    liabilities: '负债与信用',
    creditLimit: '信用额度',
    billDay: '账单日 (每月)',
    repayDay: '还款日 (每月)',
    interestRate: '年利率 (APR)',
    dueDate: '到期日',
    daysLeft: '天后到期',
    utilization: '已用额度',
    available: '可用额度',
    installments: '分期设置',
    current: '当前期数',
    total: '总期数',
    upcomingBills: '待还提醒',
    noUpcomingBills: '近期无待还账单',
    isInstallment: '分期付款?',
    period: '期',
    financialReminders: '财务提醒',
    interestFee: '利息 / 手续费',
    totalCost: '总成本',
    activeInstallments: '笔进行中的分期',
    monthlyPayment: '每月应还',
    remainingPrincipal: '剩余未还',
    earlyRepayment: '提前还款',
    confirmEarlyRepayment: '确认提前还清剩余款项吗？',
    planDetails: '分期详情',
    resetData: '清除所有数据',
    confirmReset: '确定要删除所有数据吗？此操作不可恢复。',
    resetComplete: '清理完成。',
    appearance: '界面与导航',
    showReports: '显示“统计”页面',
    showAccounts: '显示“账户”页面',

    // Batch Operations
    selected: '已选择',
    batchDelete: '删除',
    batchCancel: '取消',
    confirmBatchDelete: '确认删除选中的 {count} 笔交易吗？',

    // AI Settings
    aiConfig: 'AI 模型配置',
    provider: '厂商',
    modelName: '模型名称',
    baseUrl: 'Base URL',
    apiKeyPlaceholder: '请输入 API Key',

    // New Additions for Full Localization
    loading: 'ZenLedger 加载中...',
    importBackup: '导入备份',
    overwrite: '覆盖现有数据',
    merge: '合并到现有数据',
    customizeNav: '自定义底部导航栏',
    aiAdvisor: 'AI 财务顾问',
    monthlyAnalysis: '月度财务分析',
    thinking: '思考中...',
    kuruKuru: '正在扫描你的钱包... 发现可疑消费...',
    gotIt: '知道了',
    expensesByCat: '支出分类统计',
    incomeByCat: '收入分类统计',
    noActivePlan: '暂无进行中的分期',
    moodHappy: '开心',
    moodNeutral: '平淡',
    moodRegret: '后悔',
    moodSplurge: '挥霍',
    exchangeRate: '汇率',
    reset: '重置',
    confirm: '确认',
    installmentOn: '开启分期',
    active: '进行中',
    owed: '欠款',
    rateUpdated: '汇率更新于:',

    // New Dashboard Keys
    monthlyExpense: '本月支出',
    monthlyIncome: '本月收入',
    monthlyBalance: '本月结余',
    totalLiabilities: '总负债',
    totalAssets: '总资产',

    // Missing Keys Added
    settingsSaved: '配置已保存！',
    enterApiKey: '请输入 API 密钥',
    testingConnection: '正在测试连接...',
    connectionSuccess: '连接成功！',
    connectionFailed: '连接失败：',
    backupDownloaded: '备份已下载。',
    invalidJson: '无效的 JSON 文件或备份损坏。',
    noValidTxs: '未找到有效交易。',
    webOnly: '仅限 Web',
    webNasWarning: '由于浏览器安全限制，Web 端无法直连 NAS。已下载备份文件。',
    nasCorsWarning: '浏览器安全限制 (CORS) 可能会阻止连接到本地 NAS IP。如果连接失败，请确保您的 NAS 允许跨域请求或使用 HTTPS。',
    enterModelName: '输入模型名称 (如 gpt-4)',
    defaultUrl: '默认: https://api.deepseek.com',
    moreOptions: '更多选项...',
    charts: '图表视图',
    calendar: '日历视图',
    freshStart: '新的一月',
    startTx: '从第一笔记账开始',
    hidden: '已隐藏',
    overdue: '已逾期',
    used: '已用',
    noAccountsFound: '未找到账户！请先创建账户。',
    importPrompt: '您希望如何导入此备份？',
    planRepaid: '分期已标记为还清。',
    failedReport: '生成报告失败。',
    
    // WebDAV Specifics
    backupNow: '立即备份',
    restore: '立即恢复',
    autoSync: '启动时自动同步',
    corsError: '连接失败。可能是 CORS 跨域问题或 URL 无效。请检查控制台。',
    backingUp: '正在备份...',
    restoring: '正在恢复...',
    restoreSuccess: '从 WebDAV 恢复数据成功。',
    backupSuccess: '备份上传成功。',

    accTypes: {
      CHECKING: '储蓄卡',
      SAVINGS: '储蓄账户',
      CREDIT_CARD: '信用卡',
      CASH: '现金',
      INVESTMENT: '投资/股票',
      ALIPAY: '支付宝',
      WECHAT: '微信钱包',
      HUABEI: '花呗/白条',
      DEBT: '欠款 (我欠别人)',
      RECEIVABLE: '借出 (别人欠我)'
    }
  },
  fr: {
    dashboard: 'Aperçu',
    reports: 'Statistiques',
    accounts: 'Comptes',
    settings: 'Paramètres',
    storage: 'Stockage',
    local: 'Local',
    cloud: 'iCloud',
    nas: 'WebDAV / NAS',
    server: 'Serveur',
    totalBalance: 'Valeur Nette',
    expenses: 'Dépenses',
    income: 'Revenus',
    spendingActivity: 'Activité',
    newTransaction: 'Nouveau',
    save: 'Enregistrer',
    cancel: 'Annuler',
    parse: 'Analyse IA',
    manual: 'Manuel',
    parsing: 'Analyse...',
    description: 'Note',
    category: 'Catégorie',
    subCategory: 'Sous-catégorie',
    date: 'Date',
    amount: 'Montant',
    merchant: 'Commerçant',
    looksGood: 'Vérifier',
    edit: 'Modifier',
    saveTx: 'Sauver',
    describeTx: 'Parler ou écrire...',
    aiTip: 'ex: 20€ McDonald hier par Carte',
    myLedgers: 'Mes Budgets',
    addLedger: 'Créer Budget',
    userProfile: 'Profil',
    language: 'Langue',
    name: 'Nom',
    storageDesc: 'Paramètres de synchronisation.',
    selectCategory: 'Choisir Catégorie',
    account: 'Compte',
    type: 'Type',
    addAccount: 'Ajouter Compte',
    expense: 'Dépense',
    transfer: 'Virement',
    profile: 'Profil',
    data: 'Données',
    ledgers: 'Budgets',
    currency: 'Devise',
    initialBalance: 'Solde Initial',
    create: 'Créer',
    editLedger: 'Modifier Budget',
    currentBook: 'Budget Actuel',
    allTransactions: 'Activités Récentes',
    viewAll: 'Voir Tout',
    noTransactions: 'Aucune transaction ce mois-ci.',
    netWorth: 'Actifs Nets',
    manageCategories: 'Gérer Catégories',
    addCategory: 'Ajouter Catégorie',
    delete: 'Supprimer',
    color: 'Couleur',
    icon: 'Icône',
    history: 'Historique',
    searchPlaceholder: 'Chercher...',
    backup: 'Sauvegarde',
    export: 'Exporter (JSON)',
    import: 'Importer',
    exportDesc: 'Télécharger vos données.',
    importDesc: 'Restaurer une sauvegarde.',
    success: 'Succès',
    error: 'Erreur',
    serverAddress: 'Adresse Serveur',
    username: 'Utilisateur',
    password: 'Mot de passe',
    apiKey: 'Clé API',
    connect: 'Connecter',
    btn_test_connection: 'Tester la connexion',
    dayExp: 'Dép',
    dayInc: 'Rev',
    logOut: 'Déconnexion',
    viewProfile: 'Voir Profil',
    selectDate: 'Choisir Date',
    confirmDelete: 'Supprimer cette transaction ?',
    smartImport: 'Import Intelligent',
    screenshotImport: 'Import Capture d\'écran',
    csvImport: 'Import CSV',
    analyzing: 'Analyse de l\'image...',
    parsingCsv: 'Lecture CSV...',
    importedCount: 'transactions importées.',
    includeInTotal: 'Inclure dans le total',
    assets: 'Actifs',
    liabilities: 'Passifs',
    creditLimit: 'Limite de Crédit',
    billDay: 'Jour Facturation',
    repayDay: 'Jour Paiement',
    interestRate: 'Taux Intérêt',
    dueDate: 'Date Échéance',
    daysLeft: 'jours restants',
    utilization: 'Utilisé',
    available: 'Disponible',
    installments: 'Paiement Échelonné',
    current: 'Actuel',
    total: 'Total',
    upcomingBills: 'Factures à venir',
    noUpcomingBills: 'Aucune facture prévue.',
    isInstallment: 'Échelonnement ?',
    period: 'Période',
    financialReminders: 'Rappels',
    interestFee: 'Intérêts / Frais',
    totalCost: 'Coût Total',
    activeInstallments: 'Échelonnements Actifs',
    monthlyPayment: 'Paiement Mensuel',
    remainingPrincipal: 'Principal Restant',
    earlyRepayment: 'Remboursement Anticipé',
    confirmEarlyRepayment: 'Confirmer le remboursement anticipé ?',
    planDetails: 'Détails du Plan',
    resetData: 'Réinitialiser',
    confirmReset: 'Voulez-vous vraiment tout supprimer ?',
    resetComplete: 'Nettoyage terminé.',
    appearance: 'Apparence',
    showReports: 'Afficher Stats',
    showAccounts: 'Afficher Comptes',
    
    selected: 'Sélectionné',
    batchDelete: 'Supprimer',
    batchCancel: 'Annuler',
    confirmBatchDelete: 'Supprimer {count} transactions ?',

    aiConfig: 'Config IA',
    provider: 'Fournisseur',
    modelName: 'Nom du Modèle',
    baseUrl: 'URL de Base',
    apiKeyPlaceholder: 'Entrer Clé API',

    loading: 'Chargement...',
    importBackup: 'Importer Sauvegarde',
    overwrite: 'Écraser',
    merge: 'Fusionner',
    customizeNav: 'Menu Navigation',
    aiAdvisor: 'Conseiller IA',
    monthlyAnalysis: 'Analyse Mensuelle',
    thinking: 'Réflexion...',
    kuruKuru: 'Analyse de vos dépenses...',
    gotIt: 'Compris',
    expensesByCat: 'Dépenses par Catégorie',
    incomeByCat: 'Revenus par Catégorie',
    noActivePlan: 'Aucun plan actif.',
    moodHappy: 'Heureux',
    moodNeutral: 'Neutre',
    moodRegret: 'Regret',
    moodSplurge: 'Folie',
    exchangeRate: 'Taux de Change',
    reset: 'Réinitialiser',
    confirm: 'Confirmer',
    installmentOn: 'Activer Échelonnement',
    active: 'Actif',
    owed: 'dû',
    rateUpdated: 'Taux mis à jour:',
    
    monthlyExpense: 'Dépenses ce mois',
    monthlyIncome: 'Revenus ce mois',
    monthlyBalance: 'Solde',
    totalLiabilities: 'Total Passifs',
    totalAssets: 'Total Actifs',
    
    // Missing Keys Added (FR)
    settingsSaved: 'Paramètres enregistrés !',
    enterApiKey: 'Veuillez entrer une clé API',
    testingConnection: 'Test de connexion...',
    connectionSuccess: 'Connexion réussie !',
    connectionFailed: 'Échec de la connexion :',
    backupDownloaded: 'Sauvegarde téléchargée avec succès.',
    invalidJson: 'Fichier JSON invalide ou sauvegarde corrompue.',
    noValidTxs: 'Aucune transaction valide trouvée.',
    webOnly: 'Web Uniquement',
    webNasWarning: 'Le client Web ne peut pas se connecter au NAS (sécurité). Sauvegarde téléchargée.',
    nasCorsWarning: 'Les limitations du navigateur (CORS) peuvent bloquer la connexion au NAS local. Vérifiez les paramètres CORS du NAS ou utilisez HTTPS.',
    enterModelName: 'Entrer nom du modèle (ex: gpt-4)',
    defaultUrl: 'Défaut : https://api.deepseek.com',
    moreOptions: 'Plus d\'options...',
    charts: 'Graphiques',
    calendar: 'Calendrier',
    freshStart: 'Nouveau Départ',
    startTx: 'Commencez par votre première transaction',
    hidden: 'Masqué',
    overdue: 'En retard',
    used: 'Utilisé',
    noAccountsFound: 'Aucun compte trouvé ! Veuillez en créer un.',
    importPrompt: 'Comment voulez-vous importer cette sauvegarde ?',
    planRepaid: 'Plan marqué comme remboursé.',
    failedReport: 'Échec de la génération du rapport.',
    
    // WebDAV Specifics
    backupNow: 'Sauvegarder',
    restore: 'Restaurer',
    autoSync: 'Synchro Auto au Démarrage',
    corsError: 'Échec de la connexion (CORS ?).',
    backingUp: 'Sauvegarde...',
    restoring: 'Restauration...',
    restoreSuccess: 'Données restaurées avec succès.',
    backupSuccess: 'Sauvegarde réussie.',
    
    accTypes: {
      CHECKING: 'Compte Courant',
      SAVINGS: 'Épargne',
      CREDIT_CARD: 'Carte de Crédit',
      CASH: 'Espèces',
      INVESTMENT: 'Investissement',
      ALIPAY: 'Alipay',
      WECHAT: 'WeChat',
      HUABEI: 'Huabei',
      DEBT: 'Dette',
      RECEIVABLE: 'Créance'
    }
  }
};

export const INITIAL_USER: UserProfile = {
  name: 'Alex',
  avatar: 'https://api.dicebear.com/7.x/notionists/svg?seed=Alex',
  language: 'zh',
};

export const DEFAULT_UI_PREFS: UIPreferences = {
  showReports: true,
  showAccounts: true
};

export const INITIAL_LEDGERS: Ledger[] = [
  { id: 'l1', name: '日常开销', currency: 'CNY', color: 'bg-blue-500', icon: '🏠' },
  { id: 'l2', name: '旅行日记', currency: 'USD', color: 'bg-green-500', icon: '✈️' },
];

export const INITIAL_ACCOUNTS: Account[] = [];

export const INITIAL_CATEGORIES: Category[] = [
  { 
    id: 'c1', name: '餐饮', color: '#FF9500', icon: 'utensils', type: TransactionType.EXPENSE,
    subCategories: [
      { id: 'c1-1', name: '早餐', color: '#FF9500', icon: 'coffee', type: TransactionType.EXPENSE },
      { id: 'c1-2', name: '午晚餐', color: '#FF9500', icon: 'utensils', type: TransactionType.EXPENSE },
      { id: 'c1-3', name: '零食', color: '#FF9500', icon: 'ice-cream', type: TransactionType.EXPENSE },
    ]
  },
  { 
    id: 'c2', name: '交通', color: '#007AFF', icon: 'car', type: TransactionType.EXPENSE,
    subCategories: [
      { id: 'c2-1', name: '地铁公交', color: '#007AFF', icon: 'bus', type: TransactionType.EXPENSE },
      { id: 'c2-2', name: '打车', color: '#007AFF', icon: 'car', type: TransactionType.EXPENSE },
      { id: 'c2-3', name: '机票火车', color: '#007AFF', icon: 'plane', type: TransactionType.EXPENSE },
    ] 
  },
  { 
    id: 'c3', name: '购物', color: '#AF52DE', icon: 'shopping-bag', type: TransactionType.EXPENSE,
    subCategories: [
      { id: 'c3-1', name: '服饰', color: '#AF52DE', icon: 'shirt', type: TransactionType.EXPENSE },
      { id: 'c3-2', name: '电子产品', color: '#AF52DE', icon: 'smartphone', type: TransactionType.EXPENSE },
      { id: 'c3-3', name: '日用', color: '#AF52DE', icon: 'shopping-cart', type: TransactionType.EXPENSE },
    ]
  },
  { id: 'c4', name: '工资', color: '#34C759', icon: 'briefcase', type: TransactionType.INCOME, subCategories: [] },
  { id: 'c5', name: '娱乐', color: '#FF2D55', icon: 'film', type: TransactionType.EXPENSE, subCategories: [] },
  { id: 'c6', name: '居住', color: '#5856D6', icon: 'home', type: TransactionType.EXPENSE, subCategories: [] },
  { id: 'c7', name: '内部转账', color: '#8E8E93', icon: 'arrow-right-left', type: TransactionType.TRANSFER, subCategories: [] },
  { id: 'c8', name: '退款', color: '#34C759', icon: 'undo-2', type: TransactionType.INCOME, subCategories: [] },
];

export const INITIAL_STORAGE: StorageConfig = {
  type: 'LOCAL',
  status: 'CONNECTED',
  path: 'IndexedDB',
  autoSync: false,
};

export const ICON_MAP: Record<string, React.ReactNode> = {
  'credit-card': <CreditCard size={18} />,
  'wallet': <Wallet size={18} />,
  'banknote': <Banknote size={18} />,
  'briefcase': <Briefcase size={18} />,
  'utensils': <Utensils size={18} />,
  'car': <Car size={18} />,
  'shopping-bag': <ShoppingBag size={18} />,
  'home': <Home size={18} />,
  'film': <Film size={18} />,
  'server': <Server size={18} />,
  'smartphone': <Smartphone size={18} />,
  'cloud': <Cloud size={18} />,
  'hard-drive': <HardDrive size={18} />,
  'coffee': <Coffee size={18} />,
  'bus': <Bus size={18} />,
  'plane': <Plane size={18} />,
  'shopping-cart': <ShoppingCart size={18} />,
  'gift': <Gift size={18} />,
  'gamepad': <Gamepad2 size={18} />,
  'dumbbell': <Dumbbell size={18} />,
  'stethoscope': <Stethoscope size={18} />,
  'zap': <Zap size={18} />,
  'wifi': <Wifi size={18} />,
  'baby': <Baby size={18} />,
  'grad-cap': <GraduationCap size={18} />,
  'globe': <Globe size={18} />,
  'ice-cream': <Coffee size={18} />,
  'shirt': <ShoppingBag size={18} />,
  'trending-up': <TrendingUp size={18} />,
  'users': <Users size={18} />,
  'hand-coins': <HandCoins size={18} />,
  'arrow-right-left': <ArrowRightLeft size={18} />,
  'undo-2': <Undo2 size={18} />,
};
